version: '3'
services:
  web:
    image: ghcr.io/thevajko/vaii-web-server:main
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APP_DB_HOST=${APP_DB_HOST}
      - APP_DB_PORT=${APP_DB_PORT}
      - APP_DB_NAME=${APP_DB_NAME}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASS=${APP_DB_PASS}
      - APP_DB_CHARSET=${APP_DB_CHARSET}
    env_file:
      - .env
    volumes:
      - ../:/var/www/html/
      - ./conf.d/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "127.0.0.1:80:80"
    stdin_open: true
    tty: true


  db:
    profiles:
      - localdb
    image: mariadb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "127.0.0.1:3307:3306"
  adminer:
    profiles:
      - localdb
    links:
      - db
    depends_on:
      - db
    image: adminer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db