version: '3'
services:
  web:
    image: ghcr.io/thevajko/vaii-web-server:main
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    env_file:
      - ./../.env
    volumes:
      - ./../:/var/www/html/
    ports:
      - "127.0.0.1:80:80"
    stdin_open: true
    tty: true
  db:
    profiles:
      - localdb
    image: mariadb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "127.0.0.1:3307:3306"
  adminer:
    profiles:
      - localdb
    links:
      - db
    depends_on:
      - db
    image: adminer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db